### ISSUE TITLE
--skip-openapi-validation flag

### ISSUE THREAD

**Issue by harveycggit** [rh-integration/3scale-toolbox-jenkins#12]
Can you all describe how I would pass a flag to disable openapi validation though the toolbox?

This is related to an issue with oauth2 and openapi3 and the schema that red hat uses to validate those against, please see:

https://github.com/3scale/3scale_toolbox/issues/141#issuecomment-855844674

The flag I am trying to pass through is: --skip-openapi-validation

Thank you,
Charles Harvey

**Comment by redhatHameed** [comment]
@nmasse-itix any thoughts on this issue thanks.

**Comment by nmasse-itix** [comment]
Hello,

There is a flag that you can disable:
https://github.com/rh-integration/3scale-toolbox-jenkins/blob/d3d8ec24f844a2fc40ea863d7d50f3d3cf7865a4/src/com/redhat/OpenAPI.groovy#L11

Usually, the following instructions will do what you want:

```groovy
    service = toolbox.prepareThreescaleService(
        openapi: [filename: "hybrid-usecase-oidc/swagger.json", validateOAS: false],
        ...
   )
```

Let us know if it solves the issue!

**Comment by harveycggit** [comment]
Nicolas, I was able to set the flag:

applicationPlans: [
		            [ systemName: "${AppName}-${TargetEnvironment}", name: "${AppName}-${TargetEnvironment}", defaultPlan: true, published: true ]
		          ],
openapi: [filename: "${SwaggerFile}", validateOAS: false]

Perhaps that did take care of the original issue, but now I am encountering a new one:

12:06:17  [logs:pod/threescale-jwt-test-33-import-openapi-2qd7h] {
12:06:17  [logs:pod/threescale-jwt-test-33-import-openapi-2qd7h]   "code": "E_INVALID_URL",
12:06:17  [logs:pod/threescale-jwt-test-33-import-openapi-2qd7h]   "message": "invalid url: null",
12:06:17  [logs:pod/threescale-jwt-test-33-import-openapi-2qd7h]   "class": "ThreeScaleToolbox::InvalidUrlError"
12:06:17  [logs:pod/threescale-jwt-test-33-import-openapi-2qd7h] }

I'm not sure whether this is referring to the url in the "servers" json, or the url in the "authorizationUrl" json. I know the URL in the "servers" portion is valid... I have attached the openapi json if you can have a look.

Thank you,
Charles
[openApiToImport.txt](https://github.com/rh-integration/3scale-toolbox-jenkins/files/6632990/openApiToImport.txt)

**Comment by nmasse-itix** [comment]
It's difficult to tell without having all the arguments of toolbox.prepareThreescaleService but if you did not pass a **privateBaseUrl** in the **environment** section, the one you have in your OAS spec is definitely invalid.

Maybe could you share your Jenkins file ? it would help to point the missing parts in one go.

**Comment by harveycggit** [comment]
Thank you Nicolas. I should point out that I have no problem importing an api-key security requirement with my current pipeline, which I have attached, it's just the oath2 requirement that is giving me trouble. Note that URL_VAR_REPLACED_IN_BUILD equates to "https://dev-threescale-jwt-test.apps.non-prod.k8s.upenn.edu"
and is set (and logged so I can see it) before the json is sent to the toolbox.

Note that if I take the exact same swagger that we are sending through the toolbox and paste it directly into the ActiveDocs screen in 3scale it is accepted and works.

Working api-key annotations:

@Api()
@OpenAPIDefinition(
    security = @SecurityRequirement(name = "pennAccessTokenDefinition", scopes = {}), 
    servers = {@Server(url = "URL_VAR_REPLACED_IN_BUILD/api")},
    info = @Info(version = "1.0", description = "ISC hosted web services", title="API", contact = @Contact(name="Charles Harvey", email = "harveycg@upenn.edu")))
@SecurityScheme(in = SecuritySchemeIn.HEADER, name = "pennAccessTokenDefinition", paramName = "api-key", type = SecuritySchemeType.APIKEY)
@Component
@Singleton
@Path("/securityDefinition")
public class SwaggerSecurityDefinition {


Broken oath2 security requirement:
@Api()
@OpenAPIDefinition(
    security = @SecurityRequirement(name = "pennOauthDefinition"), 
    servers = {@Server(url = "URL_VAR_REPLACED_IN_BUILD/{defaultPath}", variables = {@ServerVariable(name = "defaultPath", defaultValue = "api")})},
    info = @Info(version = "1.0", description = "ISC hosted web services", title="API", 
     contact = @Contact(name="Charles Harvey", email = "harveycg@upenn.edu"))
    )
@SecurityScheme( name = "pennOauthDefinition", type = SecuritySchemeType.OAUTH2, 
  flows = @OAuthFlows(implicit = 
    @OAuthFlow(authorizationUrl = "https://test.aha.io/oauth/authorize", scopes = {@OAuthScope(name = "scope1", description = "scope1")})
  )
)
@Component
@Singleton
@Path("/securityDefinition")
public class SwaggerSecurityDefinition {

Jenkins: [Jenkinsfile.txt](https://github.com/rh-integration/3scale-toolbox-jenkins/files/6637880/Jenkinsfile.txt)

Best,
Charles

**Comment by nmasse-itix** [comment]
Hi Charles,

First of all, I'm able to manually import your OAS file using the threescale toolbox (without the --skip-openapi-validation flag):

```sh
$ touch ~/.3scalerc.yaml
$ mkdir -p /tmp/toolbox
$ cat > /tmp/toolbox/openApiToImport.txt <<EOF
blablabla
EOF
$ alias 3scale="podman run --name toolbox --user root --rm -v /tmp/toolbox:/tmp:z -v $HOME/.3scalerc.yaml:/opt/app-root/src/.3scalerc.yaml:z registry.redhat.io/3scale-amp2/toolbox-rhel7:3scale2.10 3scale"

$ 3scale remote add ...

$ 3scale import openapi -t test -k -d 3scale-dev /tmp/openApiToImport.txt
Created service id: 3, name: API
Service proxy updated
destroying all mapping rules
Created GET /api/securityDefinition/dummy$ endpoint
Created POST /api/v1/example/somelogic$ endpoint
Created GET /api/v1/example/retrieve/thing/{id}$ endpoint
Created POST /api/v1/example/create$ endpoint
Created GET /api/v1/sws$ endpoint
Created POST /api/v1/sws$ endpoint
Service oidc updated
```

Can you confirm it also works on your environment ? 
After the pipeline fails, can you extract the toolbox commandline from the toolbox Kubernetes job definition ? 

I had a look at your Jenkinsfile and it seems the **oidcIssuerEndpoint** is missing from the **environment** object. 

If your service is secured with oauth2, this key is mandatory (since it contains secrets, we assume it will never be in the OAS). 

https://github.com/rh-integration/3scale-toolbox-jenkins/blob/d3d8ec24f844a2fc40ea863d7d50f3d3cf7865a4/src/com/redhat/ThreescaleService.groovy#L33-L35

The syntax for the **oidcIssuerEndpoint** is: `https://client_id:client_secret@sso.host/auth/realms/your.realm` (assuming you are using Keycloak as IdP).

**Comment by harveycggit** [comment]
Nicolas, adding oidcIssuerEndpoint resulted in a successful import. I can't thank you enough for your help on this, we really appreciate it and the toolbox itself, and apologies if I missed that param in the examples.

Best, hope you have a great weekend!
Charles
